# Evaluate Benchmark

In [1]:
import sys
from pathlib import Path

project_root_candidates = [Path.cwd(), *Path.cwd().parents]
PROJECT_ROOT = next(path for path in project_root_candidates if (path / "pyproject.toml").exists())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import logging
from openai import OpenAI
import pandas as pd

from src.benchmark import BenchmarkEvaluator
from src.llm.llm import OpenAILLM


import os
from dotenv import load_dotenv
from openai import OpenAI
load_dotenv()

base_url = os.getenv('BASE_OPEN_AI_URL')
api_key = os.getenv("OPEN_AI_KEY")
client = OpenAI(api_key=api_key, base_url=base_url)

logger = logging.getLogger('benchmark_evaluation')
logger.handlers.clear()
logger.propagate = False
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter('%(message)s'))
logger.addHandler(handler)
logger.setLevel(logging.INFO)
logging.getLogger('httpx').setLevel(logging.WARNING)

/Users/danilaandreev/Documents/HSE/degree/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
llm = OpenAILLM(client, model_name='gpt-5.4')

In [3]:
from src.preprocessing import Reader, FixedCharChunker, Document, Page, Embedder, HTTPEmbedder, HTTPReader, ParagraphChunker
from src.indexing import DataStore, ChunkStore, FlatVectorStore, Index, OpenSearchBM25Store
from src.utils import AutoEDAIndex
from src.llm import OpenAILLM

DATA_STORE_DIR = PROJECT_ROOT / 'data/index/documents'
CHUNK_STORE_DIR = PROJECT_ROOT / 'data/index/chunks'
VECTOR_STORE_DIR = PROJECT_ROOT / 'data/index/vectors'
SQLITE_PATH = PROJECT_ROOT / 'data/index/db'

print(DATA_STORE_DIR)
print(CHUNK_STORE_DIR)
print(VECTOR_STORE_DIR)
print(SQLITE_PATH)

/Users/danilaandreev/Documents/HSE/degree/data/index/documents
/Users/danilaandreev/Documents/HSE/degree/data/index/chunks
/Users/danilaandreev/Documents/HSE/degree/data/index/vectors
/Users/danilaandreev/Documents/HSE/degree/data/index/db

## E1

In [4]:
from src.preprocessing import Reader, FixedCharChunker, Document, Page, Embedder, HTTPEmbedder, HTTPReader, ParagraphChunker
from src.indexing import DataStore, ChunkStore, FlatVectorStore, Index
from src.utils import AutoEDAIndex
from src.llm import OpenAILLM


DATA_STORE_DIR = PROJECT_ROOT / 'data/index/documents'
CHUNK_STORE_DIR = PROJECT_ROOT / 'data/index/chunks'
VECTOR_STORE_DIR = PROJECT_ROOT / 'data/index/vectors'
SQLITE_PATH = PROJECT_ROOT / 'data/index/db'

print(DATA_STORE_DIR)
print(CHUNK_STORE_DIR)
print(VECTOR_STORE_DIR)
print(SQLITE_PATH)

embedder = HTTPEmbedder()
dimensions = embedder.get_embeddings(['test']).shape[-1]
chunker=ParagraphChunker(
    logger=logger, 
    max_length=490, 
    overlap_sentences=1
)


index = Index(
    datastore=DataStore(str(DATA_STORE_DIR), logger),
    vectorstore=FlatVectorStore(str(VECTOR_STORE_DIR), dimensions, logger),
    chunkstore=ChunkStore(str(CHUNK_STORE_DIR), logger),
    chunker=chunker,
    embedder=embedder,
    reader=HTTPReader(),
    sqlite_path=str(SQLITE_PATH),
    logger=logger
)
    
llm = OpenAILLM(client, model_name='gpt-5.4')

/Users/danilaandreev/Documents/HSE/degree/data/index/documents
/Users/danilaandreev/Documents/HSE/degree/data/index/chunks
/Users/danilaandreev/Documents/HSE/degree/data/index/vectors
/Users/danilaandreev/Documents/HSE/degree/data/index/db

Index vectorstore loaded

In [5]:
from src.agents import V1Agent

In [6]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e1"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [7]:
e1_agent = V1Agent(index, llm, 6)

def answer_fn(question: str) -> str:
    return e1_agent.answer(question)

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

## E2

In [4]:
from opensearchpy import OpenSearch
os_client = OpenSearch(hosts=[{"host": "localhost", "port": 9201}])


embedder = HTTPEmbedder()
reader=HTTPReader()
chunker=ParagraphChunker(
    logger=logger, 
    max_length=490, 
    overlap_sentences=1
)

dimensions = embedder.get_embeddings(['test']).shape[-1]


bm25store = OpenSearchBM25Store(
    client=os_client,
    index_name=f"test_index",
    logger=logger,
)

index = Index(
    datastore=DataStore(DATA_STORE_DIR, logger),
    vectorstore=FlatVectorStore(VECTOR_STORE_DIR, dimensions, logger),
    chunkstore=ChunkStore(CHUNK_STORE_DIR, logger),
    chunker=chunker,
    embedder=embedder,
    reader=reader,
    sqlite_path=str(SQLITE_PATH),
    bm25store=bm25store,
    logger=logger
)

Index vectorstore loaded

In [5]:
from src.agents import V2Agent

In [6]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e2"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [7]:
e2_agent = V2Agent(index, llm, top_k_dense=3, top_k_bm25=3)

def answer_fn(question: str) -> str:
    return e2_agent.answer(question)

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

## E3

In [4]:
from opensearchpy import OpenSearch
os_client = OpenSearch(hosts=[{"host": "localhost", "port": 9201}])


embedder = HTTPEmbedder()
reader=HTTPReader()
chunker=ParagraphChunker(
    logger=logger, 
    max_length=490, 
    overlap_sentences=1
)

dimensions = embedder.get_embeddings(['test']).shape[-1]


bm25store = OpenSearchBM25Store(
    client=os_client,
    index_name=f"test_index",
    logger=logger,
)

index = Index(
    datastore=DataStore(DATA_STORE_DIR, logger),
    vectorstore=FlatVectorStore(VECTOR_STORE_DIR, dimensions, logger),
    chunkstore=ChunkStore(CHUNK_STORE_DIR, logger),
    chunker=chunker,
    embedder=embedder,
    reader=reader,
    sqlite_path=str(SQLITE_PATH),
    bm25store=bm25store,
    logger=logger
)

Index vectorstore loaded

In [5]:
from src.agents import V3Agent

In [6]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e3"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [7]:
e3_agent = V3Agent(index, llm, logger=logger, top_k_dense=3, top_k_bm25=3)

def answer_fn(question: str) -> str:
    return e3_agent.answer(question)

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

In [ ]:
# Пример декомпозиции

# Перечислите требования и характеристики звукоизолирующих кабин, указанные в тексте: где и для чего их следует применять, что в них следует размещать, как определяется требуемая звукоизоляция, как их следует устанавливать и какие требования предъявляются к вентиляции и внутренней отделке.
# Decompose: 
#   - Где следует применять звукоизолирующие кабины и для каких целей согласно тексту?
#   - Что следует размещать внутри звукоизолирующих кабин согласно тексту?
#   - Как определяется требуемая звукоизоляция звукоизолирующих кабин согласно тексту?
#   - Как следует устанавливать звукоизолирующие кабины согласно тексту?
#   - Какие требования предъявляются к вентиляции звукоизолирующих кабин согласно тексту?
#   - Какие требования предъявляются к внутренней отделке звукоизолирующих кабин согласно тексту?

# Сравните подземные насосные станции и погружные насосы, предусмотренные для отбора хранимых продуктов и воды из шахтных резервуаров: где именно размещается каждый вариант и при каких условиях или в каких местах допускается их установка?
# Decompose:
#   - Где размещаются подземные насосные станции, предусмотренные для отбора хранимых продуктов и воды из шахтных резервуаров?
#   - Где размещаются погружные насосы, предусмотренные для отбора хранимых продуктов и воды из шахтных резервуаров?
#   - При каких условиях или в каких местах допускается установка подземных насосных станций и погружных насосов для отбора хранимых продуктов и воды из шахтных резервуаров?
#   - Какие различия между подземными насосными станциями и погружными насосами по месту размещения и допустимым условиям установки?



# проблемный пример
# Опишите пошагово, как по тексту выполняется итерационный расчет температуры и скорости движения воздуха в прослойке, включая начальное определение температурного коэффициента и последующие пересчеты.
# Decompose:
#   - Определить исходные данные и величины, необходимые для начала итерационного расчета температуры и скорости воздуха в прослойке по тексту.
#   - Выделить шаг начального определения температурного коэффициента перед началом итераций.
#   - Описать последовательность расчета температуры воздуха в прослойке на каждой итерации.
#   - Описать последовательность расчета скорости движения воздуха в прослойке на каждой итерации.
#   - Определить правило пересчета температурного коэффициента и условия перехода к следующей итерации или завершения расчета.
#   - Собрать все шаги в единый пошаговый алгоритм итерационного расчета по тексту.
# Answer: По доступному контексту итерационный расчет температуры и скорости движения воздуха в прослойке выполняется так.

## E4

V4Agent работает как ReAct-оркестратор поверх индекса документов. На каждом шаге он строит план reasoning_steps, выбирает следующий tool-call в next_steps, выполняет один шаг, сохраняет компактный результат в историю и повторяет цикл до task_completed или достижения max_iters.

Основная логика:
- агент получает пользовательский вопрос и ведет пошаговое исследование;
- для сложных задач промпт подталкивает его к декомпозиции на маленькие подзадачи;
- основной инструмент IndexSearch принимает один узкий запрос, делает hybrid retrieval по индексу (dense + BM25, оба по 5), затем отдельным LLM-шагом сжимает найденное в структуру status + answer + useful_chunks;
- если IndexSearch считает, что ответа недостаточно, но есть полезные ссылки, агент может вызвать IndexChunkLookup и забрать точные чанки по document_name и chunk_indices;
- итоговый ответ формируется только на основе накопленных результатов из
документов.

Детали:
- история контекста хранится внутри агента и обрезается по history_limit, чтобы не раздувать prompt;
- в историю кладутся не сырые большие retrieval-результаты, а сжатые summaries tool-результатов;
- IndexSearch логирует найденные документы, страницы, chunk_index и score;
- промпт агента и описание IndexSearch специально требуют атомарных поисковых запросов: один запрос должен покрывать только один аспект;
- SearchSynthesisResult ограничен по длине, чтобы tool-ответы были короткими и пригодными для многошагового reasoning.

In [4]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e4"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [ ]:
from src.agents import create_v4_agent

e4_agent = create_v4_agent(
    client=client,
    model_name='gpt-5.4',
    logger=logger,
    bm25_index_name='test_index',
    max_top_k_dense=3,
    max_top_k_bm25=3
)

def answer_fn(question: str) -> str:
    return e4_agent.answer(question)

Index vectorstore loaded

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

## E5

Ужесточен системный промпт относительно финального ответа. Добавлены требования отвечать только по существу вопроса, включать только подтвержденную документами информацию, для сравнительных вопросов давать ответ списком по запрошенным критериям без общего вывода, для перечислений проверять полноту списка и отсутствие лишних пунктов.

In [7]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e5"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [ ]:
from src.agents import create_v5_agent

e5_agent = create_v5_agent(
    client=client,
    model_name='gpt-5.4',
    logger=logger,
    bm25_index_name='test_index',
    max_top_k_dense=3,
    max_top_k_bm25=3
)

def answer_fn(question: str) -> str:
    return e5_agent.answer(question)

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

## E6

In [4]:
BOTHUB_BASE_URL = "https://openai.bothub.chat/v1"
BOTHUB_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYzlkODEzLTFjMTAtNDhhOS1iYmJiLTBlZDMxNzRmNmM1ZiIsImlzRGV2ZWxvcGVyIjp0cnVlLCJpYXQiOjE3NzY5NDg5OTYsImV4cCI6MjA5MjUyNDk5NiwianRpIjoiU0FNenlJV0xtWEw5OUxJVCJ9.nGHQZraLM2y4su1nXTsBON2iFWrk22G7BmVNPOjF_eo"


from src.agents.clients.bothub import BothubOpenAI
local_client = BothubOpenAI(
    base_url=BOTHUB_BASE_URL,
    api_key=BOTHUB_API_KEY,
    fixed_model_name="qwen3.5-35b-a3b",
)

In [5]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e6"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [6]:
from src.agents import create_v6_agent

e6_agent = create_v6_agent(
    client=local_client,
    model_name='qwen3.5-35b-a3b',
    logger=logger,
    bm25_index_name='test_index',
    max_top_k_dense=3,
    max_top_k_bm25=3
)

def answer_fn(question: str) -> str:
    return e6_agent.answer(question)

Index vectorstore loaded

In [ ]:
# df = pd.read_csv("/Users/danilaandreev/Documents/HSE/degree/src/benchmark/results/evaluation_rag_eval_e6_20260426_173853/answers.csv")
# df = df[~((df["agent_answer"] == 'No info') & (df['question_type'] != "negative"))]
# df.to_csv("/Users/danilaandreev/Documents/HSE/degree/src/benchmark/results/evaluation_rag_eval_e6_20260426_173853/answers.csv")

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

## E7

In [80]:
judge_llm = OpenAILLM(client=client, model_name="gpt-5.4")
evaluator = BenchmarkEvaluator(judge_llm=judge_llm, logger=logger)

experiment_name = "rag_eval_e7"
benchmark_path = str(PROJECT_ROOT / "src/benchmark/results/generation_benchmark_v1_20260402_212121/benchmark.jsonl")

In [81]:
from src.tree_rag.preprocessing import TreePreprocessor
from src.tree_rag.index import TreeIndex
from src.tree_rag.agent import TreeAgent

base_url = os.getenv("BASE_OPEN_AI_URL")
api_key = os.getenv("OPEN_AI_KEY")
client = OpenAI(api_key=api_key, base_url=base_url)
reader = Reader(logger=logger)
preprocessor = TreePreprocessor(llm=llm, logger=logger)
chunker = ParagraphChunker(
    logger=logger,
    max_length=490,
    overlap_sentences=1,
)
embedder = HTTPEmbedder(logger=None)

index_dir = PROJECT_ROOT / "src" / "tree_rag" / "test_index"
tree_index = TreeIndex(
    index_dir=index_dir,
    reader=reader,
    preprocessor=preprocessor,
    chunker=chunker,
    embedder=embedder,
    logger=logger,
)

In [82]:
e7_agent = TreeAgent(
    client=client,
    model_name="gpt-5.4",
    tree_index=tree_index,
    max_iters=50,
    top_k=5,
    logger=logger
)

def answer_fn(question: str) -> str:
    return e7_agent.answer(question)

In [ ]:
result = evaluator.evaluate(
    benchmark_path=benchmark_path,
    answer_fn=answer_fn,
    experiment_name=experiment_name,
    batch=False
)

print(result["output_dir"])
result["metrics_df"]

# Журнал экспериментов

1. E1: Baseline
    - ParagraphChunker
    - dense retrieval на FRIDA
    - обычный RAG без декомпозиции
    - без итеративного цикла
    Цель: иметь референс для сравнения всех следующих шагов.

2. E2. Dense retrieval + BM25 hybrid

    Изменение: 
    - оставить dense retrieval на FRIDA
    - добавить BM25
    - зафиксировать retrieval budget как 5 dense + 5 bm25

    Гипотеза:
    - улучшится recall
    - улучшатся factual и procedure
    - особенно поможет там, где вопрос содержит редкие или буквальные термины


3. E3. Query decomposition

    Изменение:
    - перед retrieval разбивать исходный вопрос на несколько подзапросов
    - по каждому подзапросу собирать контекст
    - затем агрегировать ответ

    Гипотеза:
    - улучшатся multi_fact, comparison, procedure
    - декомпозиция даст лучший coverage для составных запросов


4. E4. ReAct-like agent with retrieval tools

    Изменение:
    - dense retrieval и BM25 становятся инструментами
    - агент в цикле сам решает:
        - какой поиск вызвать
        - сколько шагов сделать
        - когда достаточно контекста для финального ответа

    Гипотеза:
    - вырастет качество на сложных вопросах
    - особенно multi_fact, procedure, negative
    - но возможен рост latency


5. E5. Оптимизация ReAct-агента

    Изменение:
    - ограничение числа шагов
    - более жёсткие stopping rules
    - более короткие tool prompts
    - сокращение лишних вызовов retrieval / LLM

    Гипотеза:
    - сохранить или почти сохранить качество E4
    - уменьшить время ответа и стоимость inference
    
6. E6. Local models

    Изменение:
    - Использование локальной модели для оценки качества поиска

    Гипотеза:
    - На текущий момент, локальные модели способны выполнять поставленную задачу не сильно хуже 


6. E7. Изменить подход к контексту

    Хочется сделать так, чтобы агент видел весь контекст, который адаптирован на агентный подход
    Все документы должны представляться в виде дерева, по которому агент может перемещаться.
    Таким образом, агент сможет логически подходить к поиску информации. 
    И теперь, семантический поиск будет находить не конкретные документы, а находить узлы, которые агент будет обрабатывать
    Данный подход позволяет не просто более умным способом разбивать текст, а он позволяет разделить разные информационные блоки в документе
    чтобы, например, таблицы можно было обрабатывать отдельно текста, и формулы отдельно от текста.

Изменения метрик между экспериментам менее 0.05 принимаются незначимыми и относятся к погрешности оценки benchmark

In [8]:
# функция высчитывает разницу метрик между экспериментами
def compare_metric_reports(
    previous_metrics_path: str | Path,
    current_metrics_path: str | Path,
    threshold: float = 0.05,
    exclude_overall: bool = True,
) -> pd.DataFrame:
    previous_df = pd.read_csv(previous_metrics_path)
    current_df = pd.read_csv(current_metrics_path)

    if exclude_overall:
        previous_df = previous_df[previous_df["question_type"] != "overall"]
        current_df = current_df[current_df["question_type"] != "overall"]

    comparison_df = previous_df.merge(
        current_df,
        on=["question_type", "metric"],
        how="outer",
        suffixes=("_previous", "_current"),
    )

    comparison_df["delta"] = comparison_df["value_current"] - comparison_df["value_previous"]
    comparison_df["abs_delta"] = comparison_df["delta"].abs()
    comparison_df["threshold"] = threshold
    comparison_df["delta_vs_threshold"] = comparison_df["abs_delta"].apply(
        lambda value: "within_threshold" if value < threshold else "exceeds_threshold"
    )
    comparison_df["direction"] = comparison_df["delta"].apply(
        lambda delta: "up" if delta > 0 else ("down" if delta < 0 else "same")
    )

    return comparison_df[
        [
            "question_type",
            "metric",
            "value_previous",
            "value_current",
            "delta",
            "abs_delta",
            "threshold",
            "delta_vs_threshold",
            "direction",
            "count_previous",
            "count_current",
        ]
    ].sort_values(["delta_vs_threshold", "abs_delta"], ascending=[True, False])

## Описание метрик и вопросов для оценивания

  | Тип вопроса | Описание | Считаемые метрики |
  |---|---|---|
  | factual | Простой фактический вопрос с одним конкретным правильным ответом | score_accuracy |
  | choice | Вопрос с выбором одного правильного ответа из трёх вариантов | score_accuracy |
  | multi_fact | Вопрос, где ответ должен содержать несколько независимых фактов | score_precision, score_recall, score_f1, score_hallucination_rate |
  | procedure | Вопрос на пошаговую инструкцию, где важны полнота шагов и порядок | score_step_recall, score_order_accuracy, score_hallucination_rate |
  | comparison | Вопрос на сравнение двух сущностей по нескольким атрибутам | score_attribute_accuracy, score_hallucination_rate |
  | negative | Вопрос, на который в документации нет ответа, и нужен корректный отказ от выдумывания | score_abstention_accuracy, score_hallucination_rate |

| Метрика | Описание |
|---|---|
| score_accuracy | Доля полностью правильных ответов  |
| score_precision | Насколько мало лишних/ложных фактов в ответе  |
| score_recall | Насколько полно покрыты нужные факты  |
| score_f1 | Баланс полноты и точности по atomic facts  |
| score_step_recall | Доля найденных обязательных шагов  |
| score_order_accuracy | Сохранил ли порядок шагов  |
| score_attribute_accuracy | Корректность сравнения по параметрам |
| score_abstention_accuracy | Умеет ли агент корректно отказаться от ответа |
| score_hallucination_rate | Доля лишних/ложных утверждений |

## E1

In [5]:
# chunker=ParagraphChunker(
#     logger=logger, 
#     max_length=490, 
#     overlap_sentences=1
# )

In [11]:
e1_metrics_path = "src/benchmark/results/evaluation_rag_eval_e1_20260420_211717/metrics.csv"

In [ ]:
e1_metrics = pd.read_csv(str(PROJECT_ROOT / e1_metrics_path))
e1_metrics = e1_metrics[e1_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e1_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e1_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  0.950000     20
2     comparison   score_hallucination_rate  0.111667     20
1     comparison   score_attribute_accuracy  0.658333     20
3        factual             score_accuracy  0.750000     20
5     multi_fact   score_hallucination_rate  0.445635     20
4     multi_fact                   score_f1  0.493915     20
7     multi_fact               score_recall  0.498611     20
6     multi_fact            score_precision  0.554365     20
8       negative  score_abstention_accuracy  0.100000     20
9       negative   score_hallucination_rate  0.900000     20
19     procedure   score_hallucination_rate  0.345516     20
21     procedure          score_step_recall  0.534684     20
20     procedure       score_order_accuracy  1.000000     19

Усредненные результаты

                      metric     value
0  score_abstention_accuracy  0.100000
4   score_hallucination_rate  0.450704
3                   score_f1  0.493915
7               score_recall  0.498611
8          score_step_recall  0.534684
6            score_precision  0.554365
2   score_attribute_accuracy  0.658333
1             score_accuracy  0.850000
5       score_order_accuracy  1.000000

In [32]:
# df = pd.read_csv('/Users/danilaandreev/Documents/HSE/degree/src/benchmark/results/evaluation_rag_eval_e1_20260420_211717/answers.csv')

# # df = df[(df['question_type'] == 'negative') & (df['score_f1'] < 1) & (df['score_f1'] > 0.9)]['judge_result']
# df = df[(df['question_type'] == 'negative')]['judge_result']
# # display(df)
# for i in range(len(df)):
#     print(df.iloc[i])

Агент неплохо справляется с выбором ответа (здесь сразу можно допустить, что это сама LLM достаточно умная для ответа и без контекста). Также неплохие результаты в категории сравнения. Одиночные факты находит лучше, чем множество фактов. В негативных ответах агент указывает на отсутствие информации, однако он дополняет дополнительными фактами, о которых пользователь не справшивал.

## E2

In [35]:
e2_metrics_path = "src/benchmark/results/evaluation_rag_eval_e2_20260420_215136/metrics.csv"

In [36]:
e2_metrics = pd.read_csv(str(PROJECT_ROOT / e2_metrics_path))
e2_metrics = e2_metrics[e2_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e2_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e2_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  0.950000     20
2     comparison   score_hallucination_rate  0.037500     20
1     comparison   score_attribute_accuracy  0.675000     20
3        factual             score_accuracy  0.650000     20
7     multi_fact               score_recall  0.422917     20
4     multi_fact                   score_f1  0.431673     20
5     multi_fact   score_hallucination_rate  0.494020     20
6     multi_fact            score_precision  0.505980     20
8       negative  score_abstention_accuracy  0.050000     20
9       negative   score_hallucination_rate  0.950000     20
19     procedure   score_hallucination_rate  0.324405     20
21     procedure          score_step_recall  0.546907     20
20     procedure       score_order_accuracy  0.956140     19

Усредненные результаты

                      metric     value
0  score_abstention_accuracy  0.050000
7               score_recall  0.422917
3                   score_f1  0.431673
4   score_hallucination_rate  0.451481
6            score_precision  0.505980
8          score_step_recall  0.546907
2   score_attribute_accuracy  0.675000
1             score_accuracy  0.800000
5       score_order_accuracy  0.956140

In [37]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e1_metrics_path,
    PROJECT_ROOT / e2_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
3,factual,score_accuracy,0.750000,0.650000,-0.100000,0.100000,0.05,exceeds_threshold,down,20,20
7,multi_fact,score_recall,0.498611,0.422917,-0.075694,0.075694,0.05,exceeds_threshold,down,20,20
2,comparison,score_hallucination_rate,0.111667,0.037500,-0.074167,0.074167,0.05,exceeds_threshold,down,20,20
4,multi_fact,score_f1,0.493915,0.431673,-0.062241,0.062241,0.05,exceeds_threshold,down,20,20
8,negative,score_abstention_accuracy,0.100000,0.050000,-0.050000,0.050000,0.05,exceeds_threshold,down,20,20
9,negative,score_hallucination_rate,0.900000,0.950000,0.050000,0.050000,0.05,within_threshold,up,20,20
5,multi_fact,score_hallucination_rate,0.445635,0.494020,0.048385,0.048385,0.05,within_threshold,up,20,20
6,multi_fact,score_precision,0.554365,0.505980,-0.048385,0.048385,0.05,within_threshold,down,20,20
11,procedure,score_order_accuracy,1.000000,0.956140,-0.043860,0.043860,0.05,within_threshold,down,19,19
10,procedure,score_hallucination_rate,0.345516,0.324405,-0.021111,0.021111,0.05,within_threshold,down,20,20
1,comparison,score_attribute_accuracy,0.658333,0.675000,0.016667,0.016667,0.05,within_threshold,up,20,20
12,procedure,score_step_recall,0.534684,0.546907,0.012222,0.012222,0.05,within_threshold,up,20,20
0,choice,score_accuracy,0.950000,0.950000,0.000000,0.000000,0.05,within_threshold,same,20,20

Гибридный подход по большей части ухудшил метрики, скорее всего это произошло из-за уменьшения каоличества семантически близких чанков. Однако я оставлю поиск bm25, чтобы добавить разноообразия в выдаче чанков и увеличить покрытие в семантически не близких случаях.

## E3

In [12]:
e3_metrics_path = "src/benchmark/results/evaluation_rag_eval_e3_20260420_221946/metrics.csv"

In [39]:
e3_metrics = pd.read_csv(str(PROJECT_ROOT / e3_metrics_path))
e3_metrics = e3_metrics[e3_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e3_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e3_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  1.000000     20
2     comparison   score_hallucination_rate  0.140278     20
1     comparison   score_attribute_accuracy  0.654167     20
3        factual             score_accuracy  0.700000     20
7     multi_fact               score_recall  0.440278     20
5     multi_fact   score_hallucination_rate  0.451800     20
4     multi_fact                   score_f1  0.453743     20
6     multi_fact            score_precision  0.548200     20
8       negative  score_abstention_accuracy  0.100000     20
9       negative   score_hallucination_rate  0.900000     20
19     procedure   score_hallucination_rate  0.319048     20
21     procedure          score_step_recall  0.546907     20
20     procedure       score_order_accuracy  1.000000     19

Усредненные результаты

                      metric     value
0  score_abstention_accuracy  0.100000
7               score_recall  0.440278
4   score_hallucination_rate  0.452781
3                   score_f1  0.453743
8          score_step_recall  0.546907
6            score_precision  0.548200
2   score_attribute_accuracy  0.654167
1             score_accuracy  0.850000
5       score_order_accuracy  1.000000

In [42]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e2_metrics_path,
    PROJECT_ROOT / e3_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
2,comparison,score_hallucination_rate,0.037500,0.140278,0.102778,0.102778,0.05,exceeds_threshold,up,20,20
0,choice,score_accuracy,0.950000,1.000000,0.050000,0.050000,0.05,exceeds_threshold,up,20,20
8,negative,score_abstention_accuracy,0.050000,0.100000,0.050000,0.050000,0.05,exceeds_threshold,up,20,20
3,factual,score_accuracy,0.650000,0.700000,0.050000,0.050000,0.05,within_threshold,up,20,20
9,negative,score_hallucination_rate,0.950000,0.900000,-0.050000,0.050000,0.05,within_threshold,down,20,20
11,procedure,score_order_accuracy,0.956140,1.000000,0.043860,0.043860,0.05,within_threshold,up,19,19
5,multi_fact,score_hallucination_rate,0.494020,0.451800,-0.042220,0.042220,0.05,within_threshold,down,20,20
6,multi_fact,score_precision,0.505980,0.548200,0.042220,0.042220,0.05,within_threshold,up,20,20
4,multi_fact,score_f1,0.431673,0.453743,0.022069,0.022069,0.05,within_threshold,up,20,20
1,comparison,score_attribute_accuracy,0.675000,0.654167,-0.020833,0.020833,0.05,within_threshold,down,20,20
7,multi_fact,score_recall,0.422917,0.440278,0.017361,0.017361,0.05,within_threshold,up,20,20
10,procedure,score_hallucination_rate,0.324405,0.319048,-0.005357,0.005357,0.05,within_threshold,down,20,20
12,procedure,score_step_recall,0.546907,0.546907,0.000000,0.000000,0.05,within_threshold,same,20,20

В сравнении с метриками предудыщего эксперимента, улучшилась метрика категории choice, а также увеличилось количество отказов в negative сценарии

В качестве преимуществ данного метода - возможность параллельного поиска нескольких независимых запросов во время декомпозиции, так что скорость поиска может быть выше при оптимизации кода.

Однако из недостатков, можно выделить следующие проблемы:
- Если ответ уже найден в одном из итераций декомпозиции, остальные итерации будут лишними
- LLM не всегда понимает насколько сильно нужно декомпозировать исходный вопрос
- При отсутствии достаточного количества информации в финальном ответе, LLM не продолжает поиск

Для решения данных проблем, хочется перейти к более качественному подходу поиска информации, в котором LLM сам принимает решение по тому какую информацию надо искать и как это делать

## E4

In [15]:
e4_metrics_path = "src/benchmark/results/evaluation_rag_eval_e4_20260420_230209/metrics.csv"

In [8]:
e4_metrics = pd.read_csv(str(PROJECT_ROOT / e4_metrics_path))
e4_metrics = e4_metrics[e4_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e4_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e4_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  1.000000     20
2     comparison   score_hallucination_rate  0.127857     20
1     comparison   score_attribute_accuracy  0.620833     20
3        factual             score_accuracy  0.850000     20
5     multi_fact   score_hallucination_rate  0.391289     20
4     multi_fact                   score_f1  0.555323     20
7     multi_fact               score_recall  0.575449     20
6     multi_fact            score_precision  0.608711     20
8       negative  score_abstention_accuracy  0.050000     20
9       negative   score_hallucination_rate  0.950000     20
19     procedure   score_hallucination_rate  0.213996     20
21     procedure          score_step_recall  0.739286     20
20     procedure       score_order_accuracy  1.000000     19

Усредненные результаты

                      metric     value
0  score_abstention_accuracy  0.050000
4   score_hallucination_rate  0.420785
3                   score_f1  0.555323
7               score_recall  0.575449
6            score_precision  0.608711
2   score_attribute_accuracy  0.620833
8          score_step_recall  0.739286
1             score_accuracy  0.925000
5       score_order_accuracy  1.000000

In [16]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e3_metrics_path,
    PROJECT_ROOT / e4_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
12,procedure,score_step_recall,0.546907,0.739286,0.192379,0.192379,0.05,exceeds_threshold,up,20,20
3,factual,score_accuracy,0.700000,0.850000,0.150000,0.150000,0.05,exceeds_threshold,up,20,20
7,multi_fact,score_recall,0.440278,0.575449,0.135171,0.135171,0.05,exceeds_threshold,up,20,20
10,procedure,score_hallucination_rate,0.319048,0.213996,-0.105052,0.105052,0.05,exceeds_threshold,down,20,20
4,multi_fact,score_f1,0.453743,0.555323,0.101580,0.101580,0.05,exceeds_threshold,up,20,20
6,multi_fact,score_precision,0.548200,0.608711,0.060511,0.060511,0.05,exceeds_threshold,up,20,20
5,multi_fact,score_hallucination_rate,0.451800,0.391289,-0.060511,0.060511,0.05,exceeds_threshold,down,20,20
8,negative,score_abstention_accuracy,0.100000,0.050000,-0.050000,0.050000,0.05,exceeds_threshold,down,20,20
9,negative,score_hallucination_rate,0.900000,0.950000,0.050000,0.050000,0.05,within_threshold,up,20,20
1,comparison,score_attribute_accuracy,0.654167,0.620833,-0.033333,0.033333,0.05,within_threshold,down,20,20
2,comparison,score_hallucination_rate,0.140278,0.127857,-0.012421,0.012421,0.05,within_threshold,down,20,20
0,choice,score_accuracy,1.000000,1.000000,0.000000,0.000000,0.05,within_threshold,same,20,20
11,procedure,score_order_accuracy,1.000000,1.000000,0.000000,0.000000,0.05,within_threshold,same,19,19

In [17]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e1_metrics_path,
    PROJECT_ROOT / e4_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
12,procedure,score_step_recall,0.534684,0.739286,0.204601,0.204601,0.05,exceeds_threshold,up,20,20
10,procedure,score_hallucination_rate,0.345516,0.213996,-0.131520,0.131520,0.05,exceeds_threshold,down,20,20
3,factual,score_accuracy,0.750000,0.850000,0.100000,0.100000,0.05,exceeds_threshold,up,20,20
7,multi_fact,score_recall,0.498611,0.575449,0.076838,0.076838,0.05,exceeds_threshold,up,20,20
4,multi_fact,score_f1,0.493915,0.555323,0.061408,0.061408,0.05,exceeds_threshold,up,20,20
6,multi_fact,score_precision,0.554365,0.608711,0.054346,0.054346,0.05,exceeds_threshold,up,20,20
5,multi_fact,score_hallucination_rate,0.445635,0.391289,-0.054346,0.054346,0.05,exceeds_threshold,down,20,20
0,choice,score_accuracy,0.950000,1.000000,0.050000,0.050000,0.05,exceeds_threshold,up,20,20
8,negative,score_abstention_accuracy,0.100000,0.050000,-0.050000,0.050000,0.05,exceeds_threshold,down,20,20
9,negative,score_hallucination_rate,0.900000,0.950000,0.050000,0.050000,0.05,within_threshold,up,20,20
1,comparison,score_attribute_accuracy,0.658333,0.620833,-0.037500,0.037500,0.05,within_threshold,down,20,20
2,comparison,score_hallucination_rate,0.111667,0.127857,0.016190,0.016190,0.05,within_threshold,up,20,20
11,procedure,score_order_accuracy,1.000000,1.000000,0.000000,0.000000,0.05,within_threshold,same,19,19

Как видно из метрик, данный подход сильнее выделяется качеством. В первую очередь стоит отметить повышение оновных метрика качества в разных типах вопросов и уменьшение галлюцинаций.

Разберу каждую метрику и предложу решение как её улучшить:
- comparison: score_hallucination_rate & score_attribute_accuracy
Агент отвечает шире, чем спрашивают, что в реальном использовании может воспринимать основную информацию, которую искали. Надо ограничить агента, чтобы он отвечал только на те вопросы, которые нужны, без дополнения лишней информацией. \
В целом, поставить больше акцент, что агент не имеет права писать в ответе ту информацию, которая не подтверждена фактами из документов \
Такюе, агент любит сделать заключение в конце ответа, что опять же добавляет лишний шум и не соответствует поставленному вопросу

- factual: score_accuracy
Здесь агент тоже пишет больше чем нужно в ответе, но качество уже лучше

- multi_fact и procedure
Добавляет лишней информации и теряет нужный уровень абстракции, который требуется в конкретном ответе
Пока что можно добавить правило, чтобы агент в случае сложного вопроса, который требует перечисления множества фактов или пунктов, сначала убедился, что перечислил всё, а уже потом отдавал полный список, а не оставлял частичным

In [10]:
# df = pd.read_csv('/Users/danilaandreev/Documents/HSE/degree/src/benchmark/results/evaluation_rag_eval_e4_20260420_230209/answers.csv')
# df = df.drop(columns=['sample_id', 'source_path', 'page_number', 'judge_schema_name', 'criteria'])
# df = df[df['question_type'] == 'multi_fact']

# for i in range(len(df)):
#     print(i+1, end='. ')
#     dfi = df.iloc[i]
#     print(f'Question: {dfi['question']}')
#     print(f'Answer: {dfi['agent_answer']}')
#     print(f'Target: {dfi['gold_answer']}')
#     print(f'Judge: {dfi['judge_result']}')        
#     for t in ['score_accuracy', 'score_precision', 'score_recall', 'score_f1', 'score_step_recall', 'score_order_accuracy', 'score_hallucination_rate', 'score_attribute_accuracy', 'score_abstention_accuracy']:
#         if not pd.isna(dfi[t]):
#             print(f'{t}: {dfi[t]}')
#     print()

## E5

In [4]:
e5_metrics_path = "src/benchmark/results/evaluation_rag_eval_e5_20260421_231034/metrics.csv"

In [13]:
e5_metrics = pd.read_csv(str(PROJECT_ROOT / e5_metrics_path))
e5_metrics = e5_metrics[e5_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e5_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e5_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  0.950000     20
2     comparison   score_hallucination_rate  0.016667     20
1     comparison   score_attribute_accuracy  0.616667     20
3        factual             score_accuracy  0.900000     20
5     multi_fact   score_hallucination_rate  0.280298     20
7     multi_fact               score_recall  0.604668     20
4     multi_fact                   score_f1  0.624594     20
6     multi_fact            score_precision  0.719702     20
8       negative  score_abstention_accuracy  0.100000     20
9       negative   score_hallucination_rate  0.900000     20
19     procedure   score_hallucination_rate  0.062841     20
21     procedure          score_step_recall  0.766284     20
20     procedure       score_order_accuracy  1.000000     20

Усредненные результаты

                      metric     value
0  score_abstention_accuracy  0.100000
4   score_hallucination_rate  0.314951
7               score_recall  0.604668
2   score_attribute_accuracy  0.616667
3                   score_f1  0.624594
6            score_precision  0.719702
8          score_step_recall  0.766284
1             score_accuracy  0.925000
5       score_order_accuracy  1.000000

In [24]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e4_metrics_path,
    PROJECT_ROOT / e5_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
10,procedure,score_hallucination_rate,0.213996,0.062841,-0.151155,0.151155,0.05,exceeds_threshold,down,20,20
2,comparison,score_hallucination_rate,0.127857,0.016667,-0.111190,0.111190,0.05,exceeds_threshold,down,20,20
5,multi_fact,score_hallucination_rate,0.391289,0.280298,-0.110991,0.110991,0.05,exceeds_threshold,down,20,20
6,multi_fact,score_precision,0.608711,0.719702,0.110991,0.110991,0.05,exceeds_threshold,up,20,20
4,multi_fact,score_f1,0.555323,0.624594,0.069271,0.069271,0.05,exceeds_threshold,up,20,20
0,choice,score_accuracy,1.000000,0.950000,-0.050000,0.050000,0.05,exceeds_threshold,down,20,20
3,factual,score_accuracy,0.850000,0.900000,0.050000,0.050000,0.05,exceeds_threshold,up,20,20
8,negative,score_abstention_accuracy,0.050000,0.100000,0.050000,0.050000,0.05,exceeds_threshold,up,20,20
9,negative,score_hallucination_rate,0.950000,0.900000,-0.050000,0.050000,0.05,within_threshold,down,20,20
7,multi_fact,score_recall,0.575449,0.604668,0.029219,0.029219,0.05,within_threshold,up,20,20
12,procedure,score_step_recall,0.739286,0.766284,0.026999,0.026999,0.05,within_threshold,up,20,20
1,comparison,score_attribute_accuracy,0.620833,0.616667,-0.004167,0.004167,0.05,within_threshold,down,20,20
11,procedure,score_order_accuracy,1.000000,1.000000,0.000000,0.000000,0.05,within_threshold,same,19,20

In [ ]:
df = pd.read_csv('/Users/danilaandreev/Documents/HSE/degree/src/benchmark/results/evaluation_rag_eval_e5_20260421_231034/answers.csv')
df = df.drop(columns=['sample_id', 'page_number', 'judge_schema_name', 'criteria'])
df = df[df['question_type'] == 'negative']

for i in range(len(df)):
    print(i+1, end='. ')
    dfi = df.iloc[i]
    print(f'Question: {dfi['question']}')
    print(f'Answer: {dfi['agent_answer']}')
    print(f'Target: {dfi['gold_answer']}')
    print(f'Judge: {dfi['judge_result']}')  
    for t in ['score_accuracy', 'score_precision', 'score_recall', 'score_f1', 'score_step_recall', 'score_order_accuracy', 'score_hallucination_rate', 'score_attribute_accuracy', 'score_abstention_accuracy']:
        if not pd.isna(dfi[t]):
            print(f'{t}: {dfi[t]}')
    print(f'Source: {dfi['source_path']}')
    print()

Как видно качество метрик заметно выросло, но всё еще есть проблемы с покрытием в поиске. 
Возможно, агент начал бы искать более качественно, если бы на первом этапе поиска отбирал документы, которые могут быть более релевантны для поиска информации. И во время поиска сначала искал в более релевантных местах. Нужен инструмент, который позволит понять какие сейчас есть документы и что описывают

Иногда есть вопросы, просящие перечисления пунктов из главы - задача суммаризация. Тогда в данном случае, надо сделать так, чтобы агент определил в какой главе находится информация и последовательно по ней прошелся чанками для формаирования финального ответа

Самая проблемная часть всё еще в negative вопросах. Надо улучшить промпт в отношении негативных вопросов, чтобы агент не выдавал ту информацию, про которую не српашивали

## E6

In [24]:
e6_metrics_path = "src/benchmark/results/evaluation_rag_eval_e6_20260426_173853/metrics.csv"

In [25]:
e6_metrics = pd.read_csv(str(PROJECT_ROOT / e6_metrics_path))
e6_metrics = e6_metrics[e6_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e6_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e6_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  0.950000     20
2     comparison   score_hallucination_rate  0.020000     20
1     comparison   score_attribute_accuracy  0.462500     20
3        factual             score_accuracy  0.600000     20
7     multi_fact               score_recall  0.412707     20
5     multi_fact   score_hallucination_rate  0.445491     20
4     multi_fact                   score_f1  0.445810     20
6     multi_fact            score_precision  0.554509     20
8       negative  score_abstention_accuracy  0.350000     20
9       negative   score_hallucination_rate  0.650000     20
19     procedure   score_hallucination_rate  0.144127     20
21     procedure          score_step_recall  0.661869     20
20     procedure       score_order_accuracy  1.000000     20

Усредненные результаты

                      metric     value
4   score_hallucination_rate  0.314904
0  score_abstention_accuracy  0.350000
7               score_recall  0.412707
3                   score_f1  0.445810
2   score_attribute_accuracy  0.462500
6            score_precision  0.554509
8          score_step_recall  0.661869
1             score_accuracy  0.775000
5       score_order_accuracy  1.000000

In [29]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e5_metrics_path,
    PROJECT_ROOT / e6_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
3,factual,score_accuracy,0.900000,0.600000,-0.300000,0.300000,0.05,exceeds_threshold,down,20,20
9,negative,score_hallucination_rate,0.900000,0.650000,-0.250000,0.250000,0.05,exceeds_threshold,down,20,20
8,negative,score_abstention_accuracy,0.100000,0.350000,0.250000,0.250000,0.05,exceeds_threshold,up,20,20
7,multi_fact,score_recall,0.604668,0.412707,-0.191960,0.191960,0.05,exceeds_threshold,down,20,20
4,multi_fact,score_f1,0.624594,0.445810,-0.178784,0.178784,0.05,exceeds_threshold,down,20,20
5,multi_fact,score_hallucination_rate,0.280298,0.445491,0.165193,0.165193,0.05,exceeds_threshold,up,20,20
6,multi_fact,score_precision,0.719702,0.554509,-0.165193,0.165193,0.05,exceeds_threshold,down,20,20
1,comparison,score_attribute_accuracy,0.616667,0.462500,-0.154167,0.154167,0.05,exceeds_threshold,down,20,20
12,procedure,score_step_recall,0.766284,0.661869,-0.104416,0.104416,0.05,exceeds_threshold,down,20,20
10,procedure,score_hallucination_rate,0.062841,0.144127,0.081286,0.081286,0.05,exceeds_threshold,up,20,20
2,comparison,score_hallucination_rate,0.016667,0.020000,0.003333,0.003333,0.05,within_threshold,up,20,20
0,choice,score_accuracy,0.950000,0.950000,0.000000,0.000000,0.05,within_threshold,same,20,20
11,procedure,score_order_accuracy,1.000000,1.000000,0.000000,0.000000,0.05,within_threshold,same,20,20

В результате, тестирвание локальной модели Qwen 35b a3b показало сильную просадку по метрикам, но надо учесть, что основной промпт не изменялся, так что еще есть вариант улучшить качество через подгонку под конкретную модель

## E7

In [102]:
e7_metrics_path = "src/benchmark/results/evaluation_rag_eval_e7_20260502_163458/metrics.csv"

In [103]:
e7_metrics = pd.read_csv(str(PROJECT_ROOT / e7_metrics_path))
e7_metrics = e7_metrics[e7_metrics['question_type'] != 'overall']
print('Полный отчет')
display(e7_metrics.sort_values(['question_type', 'value'], ascending=True))

print('Усредненные результаты')
e7_metrics.groupby('metric', as_index=False).agg({"value": "mean"}).sort_values('value', ascending=True)

Полный отчет

   question_type                     metric     value  count
0         choice             score_accuracy  0.900000     20
2     comparison   score_hallucination_rate  0.000000     20
1     comparison   score_attribute_accuracy  0.804167     20
3        factual             score_accuracy  0.800000     20
5     multi_fact   score_hallucination_rate  0.294356     20
6     multi_fact            score_precision  0.605644     20
4     multi_fact                   score_f1  0.622031     20
7     multi_fact               score_recall  0.647702     20
8       negative  score_abstention_accuracy  0.300000     20
9       negative   score_hallucination_rate  0.700000     20
19     procedure   score_hallucination_rate  0.070536     20
21     procedure          score_step_recall  0.732662     20
20     procedure       score_order_accuracy  0.984967     17

Усредненные результаты

                      metric     value
4   score_hallucination_rate  0.266223
0  score_abstention_accuracy  0.300000
6            score_precision  0.605644
3                   score_f1  0.622031
7               score_recall  0.647702
8          score_step_recall  0.732662
2   score_attribute_accuracy  0.804167
1             score_accuracy  0.850000
5       score_order_accuracy  0.984967

In [104]:
comparison = compare_metric_reports(
    PROJECT_ROOT / e5_metrics_path,
    PROJECT_ROOT / e7_metrics_path,
    threshold=0.05,
)

display(comparison)

,question_type,metric,value_previous,value_current,delta,abs_delta,threshold,delta_vs_threshold,direction,count_previous,count_current
9,negative,score_hallucination_rate,0.900000,0.700000,-0.200000,0.200000,0.05,exceeds_threshold,down,20,20
8,negative,score_abstention_accuracy,0.100000,0.300000,0.200000,0.200000,0.05,exceeds_threshold,up,20,20
1,comparison,score_attribute_accuracy,0.616667,0.804167,0.187500,0.187500,0.05,exceeds_threshold,up,20,20
6,multi_fact,score_precision,0.719702,0.605644,-0.114058,0.114058,0.05,exceeds_threshold,down,20,20
3,factual,score_accuracy,0.900000,0.800000,-0.100000,0.100000,0.05,exceeds_threshold,down,20,20
0,choice,score_accuracy,0.950000,0.900000,-0.050000,0.050000,0.05,within_threshold,down,20,20
7,multi_fact,score_recall,0.604668,0.647702,0.043034,0.043034,0.05,within_threshold,up,20,20
12,procedure,score_step_recall,0.766284,0.732662,-0.033622,0.033622,0.05,within_threshold,down,20,20
2,comparison,score_hallucination_rate,0.016667,0.000000,-0.016667,0.016667,0.05,within_threshold,down,20,20
11,procedure,score_order_accuracy,1.000000,0.984967,-0.015033,0.015033,0.05,within_threshold,down,20,17
5,multi_fact,score_hallucination_rate,0.280298,0.294356,0.014058,0.014058,0.05,within_threshold,up,20,20
10,procedure,score_hallucination_rate,0.062841,0.070536,0.007695,0.007695,0.05,within_threshold,up,20,20
4,multi_fact,score_f1,0.624594,0.622031,-0.002563,0.002563,0.05,within_threshold,down,20,20

Результаты сопоставимы с E5 экспериментом